Blog/config/routes.rb
Rails.application.routes.draw do
  get('/posts/new', {to: 'posts#new', as: :new_post})
  post('/posts/', {to: 'posts#create', as: :posts})

  get('/posts/', {to:'posts#index'})

  get('/posts/:id', {to: 'posts#show', as: :post})

  get('/posts/:id/edit', {to: 'posts#edit', as: :edit_post})
  patch('/posts/:id', {to: 'posts#update'})
  delete('/posts/:id', {to: 'posts#destroy'})
  root('posts#index')

  resources :users, only:[:new,:create, :edit, :update]

  resource :session, only:[:new, :create, :destroy]

  resources :posts do
    resources :comments, shallow: true,  only:[:create, :destroy]
  end

  get('/users/password/:id', {to: 'users#edit_password', as: :edit_user_password})
  post('/users/password/:id', {to: 'users#update_password', as: :user_password})

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Blog/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.is_admin?
         can :manage, :all
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    can :manage, Post do |post|
      post.user == user
    end

    can :manage, Comment do |comment|
      comment.user == user 
    end


  end
end

Blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

Blog/app/models/post.rb
require 'date'
class Post < ApplicationRecord
    has_many :comments, dependent: :nullify
    belongs_to :user

    validates :title, presence: true

    validates :body,presence: true, length:{minimum: 50}

    def formatted_time
        DateTime.parse(self.created_at.to_s)
    end

    before_validation :titleize

    def titleize
        self.title = self.title.titleize if title.present?
    end



end

Blog/app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: VALID_EMAIL_REGEX
  validates :first_name,:last_name, presence: true
end

Blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def user_signed_in?
    if(session[:user_id].present? && current_user == nil )
      session[:user_id] = nil
    end
    session[:user_id].present?
  end

helper_method :user_signed_in?
helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  private

  def authenticate_user!
    if(!user_signed_in?)
      redirect_to new_user_path
    end
  end
end

Blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post, only: [:create]
  before_action :find_comment, only: [:destroy]
  before_action :authenticate_user!
  before_action :authorize_user!, only: [:destroy]

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user =current_user
    if(@comment.save)
      redirect_to post_path(@post)
    else
      render post_path(@post)
    end
  end

  def destroy
    @comment.destroy
    redirect_to post_path(@comment.post)
  end



  private
  def comment_params
    params.require(:comment).permit(:body)
  end

  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_comment
    @comment= Comment.find(params[:id])
  end

  def authorize_user!

    unless (can?(:manage, @comment) || can?(:manage, @comment.post))
      flash[:alert] = "Access denied"
      redirect_to root_path
    end
  end
end

Blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post , only:[:show, :edit, :update, :destroy]
  before_action :authorize_user!, except: [:new, :create ,  :show, :index]
  before_action :authenticate_user!, except: [:index, :show]


  def new
    @post = Post.new
  end

  def create
    @post = Post.new(get_params)
    @post.user = current_user
    
    if(@post.save)
      redirect_to posts_path
    else
      render :new
    end
  end

  def index
    @posts = Post.all.order(created_at: :desc).limit(10)
  end

  def show
    @comment = Comment.new
    @comments = Comment.all
  end

  def edit
  end

  def update

    if(@post.update get_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def get_params
    params.require(:post).permit(:title, :body)
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def authorize_user!
    unless can?(:manage, @post)
      flash[:alert] = "Access denied"
      redirect_to root_path
    end
  end

end

Blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user =  User.find_by(email: session_params[:email])
    if(user.present? && user.authenticate(session_params[:password]))
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You have signed out"
  end

  private
  def session_params
    params.require(:session).permit(:email, :password)
  end

end

Blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only:[:edit, :update,:edit_password]
  before_action :authenticate_user!, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user =User.new(user_params)
    if(@user.save)
      session[:user_id] = @user.id
      redirect_to root_path notice: "Thank you for signing up"
    else
      render :new
    end

  end



  def edit
    puts @user.id
    puts current_user
    unless @user.id == current_user.id
      flash[:alert] = "Access denied"
      redirect_to root_path
    end
  end

  def edit_password
    unless @user.id == current_user.id
      flash[:alert] = "Access denied"
      redirect_to root_path
    end
  end

  def update_password
    @user = User.find(params[:id])
    if(password_params[:new_password] == password_params[:current_password])
      flash.now[:alert] = "You must choose a new password"
      render :edit_password


    elsif(password_params[:new_password] == password_params[:confirm_password] && @user.authenticate(password_params[:current_password]))
      @user.update(password: password_params[:new_password])
      redirect_to root_path, notice: "Password successfully updated"
    else
      flash.now[:alert] = "Either your password is incorrect, or your new passwords do not match."
      render :edit_password
    end
  end

  def update
    if @user.update(user_params)
      redirect_to root_path
    else
      render :edit, alert: "Something went wrong"
    end
  end

private

def user_params
  params.require(:user).permit(:first_name,:last_name, :email, :password, :password_confirmation)
end

def password_params
  params.require(:user).permit(:current_password, :new_password, :confirm_password)
end

def find_user
  @user = User.find(params[:id])
end





end

Blog/app/helpers/application_helper.rb
module ApplicationHelper
end

Blog/app/helpers/posts_helper.rb
module PostsHelper
end

Blog/app/views/layouts/_footer.html.erb
<div class= 'container' id ="footer">
<div class= "row">
  <div class= "mr-auto">
    <ul>
      <li>
        <%= link_to "Home ", root_path %>
      </li>
      <li>
        <%= link_to "Posts ", posts_path %>
      </li>
        <li>Copyright 2017 B-log</li>

      </li>
    </ul>
  </div>
    <div class="ml-auto">
    <ul>

      <% if !user_signed_in? %>
      <li>
        <%= link_to "Sign Up ", new_user_path %>
      </li>
      <li>
        <%= link_to "Sign In ", new_session_path %>
      </li>
      <% else %>
      <li>
        <%= link_to "Sign Out ", user_path(current_user), method: :delete %>
      </li>
      <li>
        <%= link_to "Edit Your Details ", edit_user_path(current_user) %>
      </li>
      <% end %>



    </ul>
  </div>


</div>

</div>

Blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Home', root_path, class: 'navbar-brand'%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to 'New Post', new_post_path, class: 'nav-link'%>
      </li>
      <% end %>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">About us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Contact</a>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "#{current_user.first_name}", edit_user_path(current_user), class:'nav-link' %>
      </li>
        <li class='nav-item'>
        <%= link_to "Sign Out", session_path, method: :delete , class: 'nav-link' %>
      </li>
        <li class='nav-item'>
        <%= link_to "Change Password", edit_user_password_path(current_user), class: 'nav-link' %>
      </li>
      <% else %>
        <%= link_to 'Sign Up', new_user_path, class: 'nav-link' %>
        <%= link_to 'Sign In', new_session_path, class: 'nav-link' %>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<div class='container-fluid'>

     <% if flash[:notice].present? %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= flash[:notice] %>
        </div>
      <% end %>

      <% if flash[:alert].present? %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= flash[:alert] %>
        </div>
      <% end %>

    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

Blog/app/views/posts/_form.html.erb
<div class="form-page">
  <div class='container'>
    <div class="row">
      <div class="col-md-10 col-sm-12">
        <%= form_for @post do |p| %>
        <div class="form-group">
          <%= p.label :title%>
          <%= p.text_field :title %>
        </div>
        <div class="form-group">
          <%= p.label :body %>
          <%= p.text_area :body , cols: 80, rows: 50 %>
        </div>
        <%= p.submit "Update post" , class: 'btn btn-outline-dark' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

Blog/app/views/posts/edit.html.erb
<h1>Edit Post</p>
<%= render 'form' %>

Blog/app/views/posts/index.html.erb
<div class="jumbotron">
  <div class= 'row'>
    <div class="col-md-8"  >
        
        <div class="card" id = "featured">
        <%= image_tag('scene.jpg') %>
        <h4>
        <%= link_to  @posts.first.title, post_path(@posts.first) %>
        </h4>
        <p class= 'card-text'><%= @posts.first.body %></p>
        </div>
    </div>
    
    <div class="col-md-4 hidden-sm-down" id = "favorites" >
        <div class="card">
        </div>
    </div>
</div>
</div>
<div class="container">
<div class="row ">
<% @posts.each do |p| %>
<% unless(p == @posts.first) %>
<div class='col-md-4 col-sm-12'>
<div class= 'card'>
<%= image_tag('scene.jpg') %>
<h4>
<%= link_to  p.title, post_path(p) %>
</h4>
<p class= 'card-text'><%= p.body %></p>
</div>
</div>
<% end %>
<% end %>
</div>
</div>

Blog/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

Blog/app/views/posts/show.html.erb
<div class="jumbotron" id ="head-image"></div>
<div class= "row">
    <div class="col-md-2"></div>
    <div class= "col-md-8">
      <% if can?(:manage, @post) %>
        <div class='d-flex'>
            <%= link_to "Edit Post", edit_post_path(@post), class: 'btn btn-outline-dark mr-auto'%><%= link_to "Delete post", post_path(@post), method: :delete, data:{confirm: "Are you sure?"}, class: 'btn btn-outline-dark'%>
        </div>
        <% end %>
        <h1><%= @post.title %></h1>
        <p><%= @post.body %></p>

        <div class="d-flex"><div class="mr-auto">Post Category</div><div class='ml-auto'>Created: <%= time_ago_in_words( @post.formatted_time) %> ago</div>
        </div>
    </div>
</div>

<div class= "row">
    <div class= "col-md-1 col-sm-0"></div>
    <div class= "col-md-8 col-sm-12" id ="comments">
        <%= form_for [@post, @comment] do |f| %>
          <div class = "form-group">
            <%= f.label "Comment Body" %>
            <%= f.text_area :body, cols:"10", rows:"10" %>
          </div>
            <%= f.submit class: 'btn-outline-dark' %>
        <% end %>

    </div>
</div>
<div class ="row">
  <div class="col-md-3"></div>
  <div class="col-md-8">
    <
    <% @comments.each do |c| %>
      <div class="card short">
        <div class="card-body">
          <%= c.body %>
        </div>
        <% if (can?(:manage, c) || can?(:manage,@post)) %>
        <div class='card-footer'>
          <%= c.user.first_name %>
          <%= link_to "Delete", comment_path(c), method: :delete %>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

Blog/app/views/users/edit.html.erb
<div class="form-page">
<div class="row">
  <div class="col-md-3 col-sm-0">
  </div>
    <div class="col-md-6 col-sm-12">
      <h1>Edit Your Details</h1>
      <% if @user.errors.present? %>
      <%= @user.errors.full_messages.join(", ") %>
      <% end %>
      <%= form_for @user do |f| %>
      <div class='form-group'>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
      </div>
      <div class='form-group'>
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
      </div>
      <div class='form-group'>
        <%= f.label :email %>
        <%= f.email_field :email %>
      </div>
      <%= f.submit class: "btn-outline-dark" %>
      <% end %>
    </div>

</div>
</div>

Blog/app/views/users/edit_password.html.erb
<div class="form-page">
  <div class="row">
    <div class="col-md-3 col-sm-0"></div>
    <div class="col-md-6 col-sm-12">
      <h1>Update your password</h1>
      <% if @user.errors.present? %>
      <%= @user.errors.full_messages.join(", ") %>
      <% end %>
      <%= form_for :user, url: user_password_path(@user) do |f| %>
      <div class='form-group'>
        <%= f.label :current_password %>
        <%= f.password_field :current_password %>
      </div>
      <div class='form-group'>
        <%= f.label :new_password %>
        <%= f.password_field :new_password %>
      </div>
      <div class='form-group'>
        <%= f.label :confirm_password %>
        <%= f.password_field :confirm_password %>
      </div>
      <%= f.submit class: "btn-outline-dark" %>
      <% end %>
    </div>

  </div>
</div>

Blog/app/views/users/new.html.erb
<div class="form-page">
  <div class="row">
    <div class="col-md-3 col-sm-0"></div>
    <div class="col-md-6 col-sm-12">
      <h1>Sign Up</h1>
      <% if @user.errors.present? %>
      <%= @user.errors.full_messages.join(", ") %>
      <% end %>
      <%= form_for @user do |f| %>
      <div class='form-group'>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
      </div>

      <div class='form-group'>
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
      </div>

      <div class='form-group'>
        <%= f.label :email %>
        <%= f.email_field :email %>
      </div>

      <div class='form-group'>
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>

      <div class='form-group'>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </div>

      <%= f.submit class:"btn-outline-dark" %>
      <% end %>
    </div>
  </div>
</div>